// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// objective_matrix
arma::mat objective_matrix(arma::Col<int> ms, arma::vec s);
RcppExport SEXP polygrams_objective_matrix(SEXP msSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type ms(msSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(objective_matrix(ms, s));
    return rcpp_result_gen;
END_RCPP
}
// polygram_objective_vector
arma::vec polygram_objective_vector(arma::vec data, const arma::Col<int> ms, const arma::vec s);
RcppExport SEXP polygrams_polygram_objective_vector(SEXP dataSEXP, SEXP msSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::Col<int> >::type ms(msSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(polygram_objective_vector(data, ms, s));
    return rcpp_result_gen;
END_RCPP
}
