# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function calculates the objective matrix used in the quadratic
#' optimization program. It is constructed recursively from its definiton.
#'
#' @param ms an Armadillo<integer> vector containing the Bernstein degrees. Must be
#' of size |s| + 1
#' @param s an Armadillo<double> vector containing the splits, endpoints not included.
#' @return an Armadillo<double> matrix of size \code{sum(ms+1)xsum(ms+1)}.
objective_matrix <- function(ms, s) {
    .Call('polygrams_objective_matrix', PACKAGE = 'polygrams', ms, s)
}

#' A function that calculates the objective vector of a polygram. Needed for
#' the quadratic optimization routine, and can be of independent interest.
#'
#'
#' @param data a Armadillo<double> vector containing the data
#' @param ms an Armadillo<integer> vector containing the Bernstein degrees. Must be
#' of size |s| + 1
#' @param s_aug an Armadillo<double> vector containing the splits, endpoints not included.
#' @return an Armadillo<double> of size \code{sum(ms+1)} that contains the
#' objective vector for the optimization program.
polygram_objective_vector <- function(data, ms, s) {
    .Call('polygrams_polygram_objective_vector', PACKAGE = 'polygrams', data, ms, s)
}

